
import java.util.Arrays;
import javax.swing.ListModel;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucasdelpozo
 */
public class TelaSerieB extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaSerieB.class.getName()); 
    
    /**
     * Creates new form TelaSerieB
     */
    public TelaSerieB() {
        initComponents();
        
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();

center.setHorizontalAlignment(SwingConstants.CENTER);

for (int i = 0; i < tblJogos.getColumnCount(); i++) {
    tblJogos.getColumnModel().getColumn(i).setCellRenderer(center);
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstTimes = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJogos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        bttnGerar = new javax.swing.JButton();
        bttnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstTimes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "América Mineiro", "Athletic Club", "Atlético Goianiense", "Avaí", "Botafogo-SP", "Ceará", "CRB", "Criciúma", "Cuiabá", "Fortaleza", "Goiás", "Juventude", "Londrina", "Náutico", "Novorizontino", "Operário-PR", "Ponte Preta", "São Bernardo", "Sport", "Vila Nova" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstTimes);

        tblJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Local", "", "x", "", "Visitante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblJogos);
        if (tblJogos.getColumnModel().getColumnCount() > 0) {
            tblJogos.getColumnModel().getColumn(0).setPreferredWidth(180);
            tblJogos.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblJogos.getColumnModel().getColumn(2).setPreferredWidth(30);
            tblJogos.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblJogos.getColumnModel().getColumn(4).setPreferredWidth(180);
        }

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Time", "P", "V", "E", "D", "GP", "GN", "SG"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblTabela);
        if (tblTabela.getColumnModel().getColumnCount() > 0) {
            tblTabela.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblTabela.getColumnModel().getColumn(1).setPreferredWidth(30);
            tblTabela.getColumnModel().getColumn(2).setPreferredWidth(30);
            tblTabela.getColumnModel().getColumn(3).setPreferredWidth(30);
            tblTabela.getColumnModel().getColumn(4).setPreferredWidth(30);
            tblTabela.getColumnModel().getColumn(5).setPreferredWidth(30);
            tblTabela.getColumnModel().getColumn(6).setPreferredWidth(30);
            tblTabela.getColumnModel().getColumn(7).setPreferredWidth(30);
        }

        bttnGerar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bttnGerar.setText("Gerar");
        bttnGerar.addActionListener(this::bttnGerarActionPerformed);

        bttnLimpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bttnLimpar.setText("Limpar");
        bttnLimpar.addActionListener(this::bttnLimparActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bttnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnGerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttnGerar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttnLimpar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String[] vetorNomes = new String[20];
    int[] vetorP = new int[20], vetorV = new int[20], vetorE = new int[20], vetorD = new int[20], vetorGP = new int[20], vetorGN = new int[20], vetorSG = new int[20];
    
    private void pegarTimes(){
                ListModel model = lstTimes.getModel();

        for (int i = 0; i < model.getSize(); i++) {
        vetorNomes[i] = model.getElementAt(i).toString();
        }
    }
    
    private void simJogo(){
        DefaultTableModel model =
    (DefaultTableModel) tblJogos.getModel();
        
        int casa = 0, visitante = 0;
        
        for(int i = 0; i < 20; i++){
            for(int j = 0; j < 20; j++){
                if(j != i){
                    casa = (int)(Math.random() * 6) + 1;
                    visitante = (int)(Math.random() * 6) + 1;
                    
                    if (casa > visitante){
                        vetorP[i] += 3;
                        vetorV[i] ++;
                        vetorGP[i] += casa;
                        vetorGN[i] += visitante;
                        vetorSG[i] += casa - visitante;
                        
                        vetorD[j] ++;
                        vetorGP[j] += visitante;
                        vetorGN[j] += casa;
                        vetorSG[j] += visitante - casa;
                    }
                    if (visitante > casa){
                        vetorP[j] += 3;
                        vetorV[j] ++;
                        vetorGP[j] += visitante;
                        vetorGN[j] += casa;
                        vetorSG[j] += visitante - casa;
                        
                        vetorD[i] ++;
                        vetorGP[i] += casa;
                        vetorGN[i] += visitante;
                        vetorSG[i] += casa - visitante;
                    }
                    if (visitante == casa){
                        vetorP[i] += 1;
                        vetorE[i] ++;
                        vetorGP[i] += casa;
                        vetorGN[i] += visitante;
                        vetorSG[i] += casa - visitante;
                        
                        vetorP[j] += 1;
                        vetorE[j] ++;
                        vetorGP[j] += visitante;
                        vetorGN[j] += casa;
                        vetorSG[j] += visitante - casa;
                    }
                    
                    model.addRow(new Object[]{
                    vetorNomes[i],
                        casa,
                        "x",
                        visitante,
                    vetorNomes[j]
                    });
                }      
            }// forj
        }// fori
    }
    
    private void gerarTabela(){
        DefaultTableModel model =
    (DefaultTableModel) tblTabela.getModel();
        
        for(int i = 0; i < 20; i++){
            model.addRow(new Object[]{
                    vetorNomes[i],
                    vetorP[i],
                    vetorV[i],
                    vetorE[i],
                    vetorD[i],
                    vetorGP[i],
                    vetorGN[i],
                    vetorSG[i]
                    });
        }

TableRowSorter<DefaultTableModel> sorter =
    new TableRowSorter<>(model);

tblTabela.setRowSorter(sorter);

sorter.setSortKeys(Arrays.asList(
    new RowSorter.SortKey(1, SortOrder.DESCENDING), // pontos
    new RowSorter.SortKey(2, SortOrder.DESCENDING), // vitórias
    new RowSorter.SortKey(7, SortOrder.DESCENDING), // saldo
    new RowSorter.SortKey(5, SortOrder.DESCENDING)  // gols pró
));
    }
    
    private void bttnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnGerarActionPerformed
        // TODO add your handling code here:
           pegarTimes();
           simJogo();
           gerarTabela();
    }//GEN-LAST:event_bttnGerarActionPerformed

    private void bttnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnLimparActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelJogos =
    (DefaultTableModel) tblJogos.getModel();

    DefaultTableModel modelTabela =
    (DefaultTableModel) tblTabela.getModel();

    modelJogos.setRowCount(0);

    modelTabela.setRowCount(0);
    
    for(int i = 0; i < 20; i++){
        vetorP[i] = 0;
        vetorV[i] = 0;
        vetorE[i] = 0;
        vetorD[i] = 0;
        vetorGP[i] = 0;
        vetorGN[i] = 0;
        vetorSG[i] = 0;
}
    }//GEN-LAST:event_bttnLimparActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaSerieB().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnGerar;
    private javax.swing.JButton bttnLimpar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstTimes;
    private javax.swing.JTable tblJogos;
    private javax.swing.JTable tblTabela;
    // End of variables declaration//GEN-END:variables
}
