/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author profi
 */
public class TelaAula08 extends javax.swing.JFrame {

    /**
     * Creates new form TelaAula08
     */
    public TelaAula08() {
        initComponents();
        lblresposta.setText("<html>Adivinhe o numero\n de 1 a 5 que estou pensando</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblresposta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spnnrpalpite = new javax.swing.JSpinner();
        bttnpalpite = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblresposta.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        lblresposta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblresposta.setText("frase");
        getContentPane().add(lblresposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 140, 100));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Valor:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 215, -1, -1));

        spnnrpalpite.setModel(new javax.swing.SpinnerNumberModel(1, null, 5, 1));
        getContentPane().add(spnnrpalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 214, 52, -1));

        bttnpalpite.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bttnpalpite.setText("Palpite");
        bttnpalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnpalpiteActionPerformed(evt);
            }
        });
        getContentPane().add(bttnpalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/genio1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dialogo (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 261, 177));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnpalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnpalpiteActionPerformed
        // TODO add your handling code here:
        double n = 1 + Math.random() * (6-1); 
        int pens = (int) n;
        
        int palpite = Integer.parseInt(spnnrpalpite.getValue().toString());
        
        String f1 = "<html>ACERTOU, parabens!!!</html>";
        String f2 = "<html>ERROU, eu tinha pensado em " + pens + "</html>";
        
        String res = (pens == palpite)?f1:f2;
        lblresposta.setText(res);
    }//GEN-LAST:event_bttnpalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAula08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAula08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAula08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAula08.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAula08().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnpalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblresposta;
    private javax.swing.JSpinner spnnrpalpite;
    // End of variables declaration//GEN-END:variables
}
