/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aula19;

/**
 *
 * @author lucasdelpozo
 */
public class TelaControleRemoto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaControleRemoto.class.getName());

    /**
     * Creates new form TelaControleRemoto
     */
    public TelaControleRemoto() {
        
        initComponents();
        
        lblLigada.setVisible(false);
        lblVolume.setVisible(false);
        lblPause.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bttnLigar = new javax.swing.JButton();
        bttnMaisVolume = new javax.swing.JButton();
        bttnMenosVolume = new javax.swing.JButton();
        bttnPause = new javax.swing.JButton();
        bttnResume = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblPause = new javax.swing.JLabel();
        lblVolume = new javax.swing.JLabel();
        lblLigada = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        bttnLigar.setText("⏻");
        bttnLigar.addActionListener(this::bttnLigarActionPerformed);

        bttnMaisVolume.setText("+");
        bttnMaisVolume.addActionListener(this::bttnMaisVolumeActionPerformed);

        bttnMenosVolume.setText("-");
        bttnMenosVolume.addActionListener(this::bttnMenosVolumeActionPerformed);

        bttnPause.setText("⏸");
        bttnPause.addActionListener(this::bttnPauseActionPerformed);

        bttnResume.setText("▶");
        bttnResume.addActionListener(this::bttnResumeActionPerformed);

        jButton1.setText("🔇");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttnPause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnResume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttnMaisVolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnMenosVolume, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bttnLigar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(bttnLigar)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnMaisVolume)
                    .addComponent(bttnPause))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttnMenosVolume)
                    .addComponent(bttnResume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(68, 68, 68))
        );

        lblPause.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblPause.setForeground(new java.awt.Color(0, 204, 102));
        lblPause.setText("A tv esta pausada.");

        lblVolume.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblVolume.setForeground(new java.awt.Color(0, 204, 102));

        lblLigada.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblLigada.setForeground(new java.awt.Color(0, 204, 102));
        lblLigada.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLigada)
                    .addComponent(lblPause))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(lblLigada)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPause, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    ControleRemoto c = new ControleRemoto();
    
    private void bttnMaisVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnMaisVolumeActionPerformed
        // TODO add your handling code here:
        if(c.getVolume() < 100){
        c.maisVolume();
        lblVolume.setText("Volume: " + Integer.toString(c.getVolume()));
        }
    }//GEN-LAST:event_bttnMaisVolumeActionPerformed

    private void bttnLigarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnLigarActionPerformed
        // TODO add your handling code here:
        if(!c.getLigado()){
            c.ligar();
            lblLigada.setText("A tv esta ligada");
            lblLigada.setVisible(true);
            lblVolume.setVisible(true);
        } else {
            c.desligar();
            lblLigada.setText("A tv foi desligada");
            lblPause.setVisible(false);
            lblVolume.setVisible(false);
        }
        
    }//GEN-LAST:event_bttnLigarActionPerformed

    private void bttnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnPauseActionPerformed
        // TODO add your handling code here:
        if(c.getLigado()){
            c.pause();
            lblPause.setText("A tv esta pausada");
            lblPause.setVisible(true);
        }
    }//GEN-LAST:event_bttnPauseActionPerformed

    private void bttnResumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnResumeActionPerformed
        // TODO add your handling code here:
        if(!c.getTocando() && c.getLigado()){
            c.play();
            lblPause.setText("A tv esta tocando");
            lblPause.setVisible(true);
        }
        
    }//GEN-LAST:event_bttnResumeActionPerformed

    private void bttnMenosVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnMenosVolumeActionPerformed
        // TODO add your handling code here:
        if(c.getVolume() > 0){
        c.menosVolume();
        lblVolume.setText("Volume: " + Integer.toString(c.getVolume()));
        }
    }//GEN-LAST:event_bttnMenosVolumeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        c.ligarMudo();
        lblVolume.setText("Volume: 0");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaControleRemoto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnLigar;
    private javax.swing.JButton bttnMaisVolume;
    private javax.swing.JButton bttnMenosVolume;
    private javax.swing.JButton bttnPause;
    private javax.swing.JButton bttnResume;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLigada;
    private javax.swing.JLabel lblPause;
    private javax.swing.JLabel lblVolume;
    // End of variables declaration//GEN-END:variables
}
