/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author lucasdelpozo
 */
public class TelaJogoDaVelha extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaJogoDaVelha.class.getName());

    /**
     * Creates new form TelaJogoDaVelha
     */
    public TelaJogoDaVelha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttn11 = new javax.swing.JButton();
        bttn12 = new javax.swing.JButton();
        bttn13 = new javax.swing.JButton();
        bttn23 = new javax.swing.JButton();
        bttn33 = new javax.swing.JButton();
        bttn22 = new javax.swing.JButton();
        bttn32 = new javax.swing.JButton();
        bttn21 = new javax.swing.JButton();
        bttn31 = new javax.swing.JButton();
        lblVez = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblVitoria = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mntmSair = new javax.swing.JMenuItem();
        mntmNovo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bttn11.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        bttn11.addActionListener(this::bttn11ActionPerformed);

        bttn12.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        bttn12.addActionListener(this::bttn12ActionPerformed);

        bttn13.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        bttn13.addActionListener(this::bttn13ActionPerformed);

        bttn23.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        bttn23.addActionListener(this::bttn23ActionPerformed);

        bttn33.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        bttn33.addActionListener(this::bttn33ActionPerformed);

        bttn22.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        bttn22.addActionListener(this::bttn22ActionPerformed);

        bttn32.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        bttn32.addActionListener(this::bttn32ActionPerformed);

        bttn21.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        bttn21.addActionListener(this::bttn21ActionPerformed);

        bttn31.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        bttn31.addActionListener(this::bttn31ActionPerformed);

        lblVez.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblVez.setForeground(new java.awt.Color(255, 0, 0));
        lblVez.setText("X");

        lblEstado.setText("Vez do Jogador:");

        lblVitoria.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jMenu1.setText("File");

        mntmSair.setText("Sair");
        mntmSair.addActionListener(this::mntmSairActionPerformed);
        jMenu1.add(mntmSair);

        mntmNovo.setText("Novo");
        mntmNovo.addActionListener(this::mntmNovoActionPerformed);
        jMenu1.add(mntmNovo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVez)
                        .addGap(182, 182, 182))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttn11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttn21, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttn31, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttn22, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttn23, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttn32, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bttn33, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttn12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(bttn13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVitoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVez)
                    .addComponent(lblEstado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttn11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttn12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttn13, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttn23, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttn22, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttn21, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttn31, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttn32, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttn33, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVitoria, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int x = 1, v = 0, i = 0;
    int c11, c12, c13, c21, c22, c23, c31, c32, c33;
    
    
    
    private void vez(){
        if (v == 1 || i == 9){
            return;
        }
        if (x == 1){
            lblVez.setText("X");
        }else{
            lblVez.setText("O");
        }
}
    
    private void ganhar(){
        int l1, l2, l3, k1, k2, k3, d1, d2;
        l1 = c11 + c12 + c13;
        l2 = c21 + c22 + c23;
        l3 = c31 + c32 + c33;
        
        k1 = c11 + c21 + c31;
        k2 = c12 + c22 + c32;
        k3 = c13 + c23 + c33;
        
        d1 = c11 + c22 + c33;
        d2 = c13 + c22 + c31;
        
        if (l1 == 3 || l2 == 3 || l3 == 3 || k1 == 3 || k2 == 3 || k3 == 3 || d1 == 3 || d2 == 3){
            lblVitoria.setText("O jogador X Ganhou!!!");
            lblEstado.setText("Fim de Jogo!!!");
            lblVez.setText(" - ");
            v = 1;
        }
        if (l1 == -3 || l2 == -3 || l3 == -3 || k1 == -3 || k2 == -3 || k3 == -3 || d1 == -3 || d2 == -3){
            lblVitoria.setText("O jogador O Ganhou!!!");
            lblEstado.setText("Fim de Jogo!!!");
            lblVez.setText(" - ");
            v = 1;
        }
        if (v!= 1 && i == 9){
            lblVitoria.setText("O jogo terminou empatado!!!");
            lblEstado.setText("Fim de Jogo!!!");
            lblVez.setText(" - ");
        }
    }
    
    private void bttn31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn31ActionPerformed
        // TODO add your handling code here:
        if (x == 1){
            bttn31.setText("X");
            c31 = 1;
            x = 0;
        }else{
            bttn31.setText("O");
            c31 = -1;
            x = 1;
        }
        bttn31.setEnabled(false);
        i ++;
        ganhar();
        vez();
    }//GEN-LAST:event_bttn31ActionPerformed

    private void bttn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn11ActionPerformed
        // TODO add your handling code here:
        if (x == 1){
            bttn11.setText("X");
            c11 = 1;
            x = 0;
        }else{
            bttn11.setText("O");
            c11 = -1;
            x = 1;
        }
        bttn11.setEnabled(false);
        i ++;
        ganhar();
        vez();
    }//GEN-LAST:event_bttn11ActionPerformed

    private void bttn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn12ActionPerformed
        // TODO add your handling code here:
        if (x == 1){
            bttn12.setText("X");
            c12 = 1;
            x = 0;
        }else{
            bttn12.setText("O");
            c12 = -1;
            x = 1;
        }
        bttn12.setEnabled(false);
        i ++;
        ganhar();
        vez();
    }//GEN-LAST:event_bttn12ActionPerformed

    private void bttn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn13ActionPerformed
        // TODO add your handling code here:
        if (x == 1){
            bttn13.setText("X");
            c13 = 1;
            x = 0;
        }else{
            bttn13.setText("O");
            c13 = -1;
            x = 1;
        }
        bttn13.setEnabled(false);
        i ++;
        ganhar();
        vez();
    }//GEN-LAST:event_bttn13ActionPerformed

    private void bttn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn21ActionPerformed
        // TODO add your handling code here:
        if (x == 1){
            bttn21.setText("X");
            c21 = 1;
            x = 0;
        }else{
            bttn21.setText("O");
            c21 = -1;
            x = 1;
        }
        bttn21.setEnabled(false);
        i ++;
        ganhar();
        vez();
    }//GEN-LAST:event_bttn21ActionPerformed

    private void bttn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn22ActionPerformed
        // TODO add your handling code here:
        if (x == 1){
            bttn22.setText("X");
            c22 = 1;
            x = 0;
        }else{
            bttn22.setText("O");
            c22 = -1;
            x = 1;
        }
        bttn22.setEnabled(false);
        i ++;
        ganhar();
        vez();
    }//GEN-LAST:event_bttn22ActionPerformed

    private void bttn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn23ActionPerformed
        // TODO add your handling code here:
        if (x == 1){
            bttn23.setText("X");
            c23 = 1;
            x = 0;
        }else{
            bttn23.setText("O");
            c23 = -1;
            x = 1;
        }
        bttn23.setEnabled(false);
        i ++;
        ganhar();
        vez();
    }//GEN-LAST:event_bttn23ActionPerformed

    private void bttn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn32ActionPerformed
        // TODO add your handling code here:
        if (x == 1){
            bttn32.setText("X");
            c32 = 1;
            x = 0;
        }else{
            bttn32.setText("O");
            c32 = -1;
            x = 1;
        }
        bttn32.setEnabled(false);
        i ++;
        ganhar();
        vez();
    }//GEN-LAST:event_bttn32ActionPerformed

    private void bttn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn33ActionPerformed
        // TODO add your handling code here:
        if (x == 1){
            bttn33.setText("X");
            c33 = 1;
            x = 0;
        }else{
            bttn33.setText("O");
            c33 = -1;
            x = 1;
        }
        bttn33.setEnabled(false);
        i ++;
        ganhar();
        vez();
    }//GEN-LAST:event_bttn33ActionPerformed

    private void mntmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntmSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mntmSairActionPerformed

    private void mntmNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntmNovoActionPerformed
        // TODO add your handling code here:
        v = 0;
        i = 0;
        c11 = 0; c12 = 0; c13 = 0; c21 = 0; c22 = 0; c23 = 0; c31 = 0; c32 = 0; c33 = 0;
        bttn11.setEnabled(true); 
        bttn12.setEnabled(true);
        bttn13.setEnabled(true);
        bttn21.setEnabled(true);
        bttn22.setEnabled(true);
        bttn23.setEnabled(true);
        bttn31.setEnabled(true);
        bttn32.setEnabled(true);
        bttn33.setEnabled(true);
        
        bttn11.setText(" ");
        bttn12.setText(" ");
        bttn13.setText(" ");
        bttn21.setText(" ");
        bttn22.setText(" ");
        bttn23.setText(" ");
        bttn31.setText(" ");
        bttn32.setText(" ");
        bttn33.setText(" ");
        
        if (x == 1){
            lblVez.setText("X");
        }else{
            lblVez.setText("O");
        }
    }//GEN-LAST:event_mntmNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaJogoDaVelha().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn11;
    private javax.swing.JButton bttn12;
    private javax.swing.JButton bttn13;
    private javax.swing.JButton bttn21;
    private javax.swing.JButton bttn22;
    private javax.swing.JButton bttn23;
    private javax.swing.JButton bttn31;
    private javax.swing.JButton bttn32;
    private javax.swing.JButton bttn33;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblVez;
    private javax.swing.JLabel lblVitoria;
    private javax.swing.JMenuItem mntmNovo;
    private javax.swing.JMenuItem mntmSair;
    // End of variables declaration//GEN-END:variables
}
