/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author profi
 */
public class TelaIMC extends javax.swing.JFrame {

    /**
     * Creates new form TelaIMC
     */
    public TelaIMC() {
        initComponents();
        pnlresult.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttngrpSexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        pnlresult = new javax.swing.JPanel();
        lblimc = new javax.swing.JLabel();
        lblcondicao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfldPeso = new javax.swing.JTextField();
        txtfldAltura = new javax.swing.JTextField();
        rdbttnMasc = new javax.swing.JRadioButton();
        rdbttnFem = new javax.swing.JRadioButton();
        bttnCalc = new javax.swing.JButton();
        bttnLimpar = new javax.swing.JButton();
        lblerro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel1.setText("Selecione:");

        lblimc.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N

        lblcondicao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblcondicao.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlresultLayout = new javax.swing.GroupLayout(pnlresult);
        pnlresult.setLayout(pnlresultLayout);
        pnlresultLayout.setHorizontalGroup(
            pnlresultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlresultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlresultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblimc)
                    .addComponent(lblcondicao))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        pnlresultLayout.setVerticalGroup(
            pnlresultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlresultLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblimc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblcondicao)
                .addGap(21, 21, 21))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Peso (Kg):");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Altura (m):");

        txtfldPeso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txtfldAltura.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        bttngrpSexo.add(rdbttnMasc);
        rdbttnMasc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdbttnMasc.setText("Masculino");

        bttngrpSexo.add(rdbttnFem);
        rdbttnFem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdbttnFem.setText("Feminino");

        bttnCalc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bttnCalc.setText("Calcular");
        bttnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCalcActionPerformed(evt);
            }
        });

        bttnLimpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bttnLimpar.setText("Limpar");
        bttnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnLimparActionPerformed(evt);
            }
        });

        lblerro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblerro.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtfldAltura)
                            .addComponent(txtfldPeso)
                            .addComponent(rdbttnMasc)
                            .addComponent(rdbttnFem))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bttnCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblerro, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlresult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(rdbttnMasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbttnFem)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnCalc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfldAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblerro, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlresult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCalcActionPerformed
        // TODO add your handling code here:
        
        if (txtfldPeso.getText().isEmpty() || txtfldAltura.getText().isEmpty()) {
        lblerro.setText("Preencha todos os campos");
        return;
        } else {
            lblerro.setText(" ");
        }
        
        try{
        
        String altura = txtfldAltura.getText().replace(",", ".");
        String peso = txtfldPeso.getText().replace(",", ".");
        
        float h = Float.parseFloat(altura);
        float p = Float.parseFloat(peso);
        
        float imc = p / (h * h);
        float imcround = Math.round(imc * 1000) / 1000f;
        
        lblimc.setText("IMC: "+ imcround);
   
        if (rdbttnFem.isSelected()) {
            if (imc < 19.1){
                lblcondicao.setText("Abaixo do peso.");
            } else if (imc > 19.1 && imc < 25.8){
                lblcondicao.setText("No peso normal.");
            } else if (imc > 25.8 && imc < 27.3){
                lblcondicao.setText("Marginalmente acima do peso.");
            } else if (imc > 27.3 && imc < 32.3){
                lblcondicao.setText("Acima do peso ideal.");
            } else if (imc > 32.3){
                lblcondicao.setText("Obeso.");
            }
        } else if (rdbttnMasc.isSelected()) {
            if (imc < 20.7){
                lblcondicao.setText("Abaixo do peso.");
            } else if (imc > 20.7 && imc < 26.4){
                lblcondicao.setText("No peso normal.");
            } else if (imc > 26.4 && imc < 27.8){
                lblcondicao.setText("Marginalmente acima do peso.");
            } else if (imc > 27.8 && imc < 31.1){
                lblcondicao.setText("Acima do peso ideal.");
            } else if (imc > 31.1){
                lblcondicao.setText("Obeso.");
            }
        } else {
            lblcondicao.setText("Sexo nao selecionado, favor selecionar.");
        }
        
        pnlresult.setVisible(true);
        
        } catch (NumberFormatException e) {
        lblerro.setText("Digite apenas números válidos para peso e altura");
        }
    }//GEN-LAST:event_bttnCalcActionPerformed

    private void bttnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnLimparActionPerformed
        // TODO add your handling code here:
        bttngrpSexo.clearSelection();
        
        txtfldPeso.setText("");
        txtfldAltura.setText("");
        lblerro.setText(" ");
        
        pnlresult.setVisible(false);
    }//GEN-LAST:event_bttnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIMC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaIMC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCalc;
    private javax.swing.JButton bttnLimpar;
    private javax.swing.ButtonGroup bttngrpSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblcondicao;
    private javax.swing.JLabel lblerro;
    private javax.swing.JLabel lblimc;
    private javax.swing.JPanel pnlresult;
    private javax.swing.JRadioButton rdbttnFem;
    private javax.swing.JRadioButton rdbttnMasc;
    private javax.swing.JTextField txtfldAltura;
    private javax.swing.JTextField txtfldPeso;
    // End of variables declaration//GEN-END:variables
}
